-- DEPRECATED: this file has been decomposed into lua/tttbots2/components/chatter/
-- The entry point is sv_chatter_core.lua, which is loaded by sh_botlib.lua.
-- This file is intentionally empty to prevent double-loading.
