--- cl_TTS.lua — Client-side audio playback
---
--- Moved to the standalone `ttt2-tts` addon (cl_tts_player.lua).
--- This file is kept as an empty stub so sh_tttbots2.lua's include() keeps
--- working; remove the include in future versions once bot servers have
--- migrated to ttt2-tts.
